apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: svelte-client
  name: svelte-client
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: svelte-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: svelte-client
    spec:
      containers:
      - image: tbaums/svelte-client:latest
        imagePullPolicy: Always
        name: svelte-client
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          #TODO: get TLS working because this is v dangerous
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
        - name: KAFKA_READ_URL
          value: 'https://aa5075ebba40811e9a7850aec40aad68-946518783.us-west-2.elb.amazonaws.com/kafka-client-api/read?topic=topic57'
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5
status: {}
